### PR TITLE
Added computeAbsoluteHumidity

### PR DESCRIPTION
**Pull request by tonnico**
This patch has two commits.

First one simply brings the tabs/spaces consistent with the rest of the code.
Second one added an absolute humidity calculation. Check [this link](https://carnotcycle.wordpress.com/2012/08/04/how-to-convert-relative-humidity-to-absolute-humidity/).

You may push a new 1.0.10 tag, already setup in the library-files.

### CODE REVIEW

**Comment by beegee-tokyo** [comment]
Nice, thank you.
Will give it a test when I am back from vacations mid of March and merge the commit.

**Comment by tonnico** [comment]
You're welcome. 

~~Just found a small mistake. It's g/m^3 not g/mm^3. I will fix it~~ Fixed

**Comment by beegee-tokyo** [comment]
Please clarify:
You declare the function with
**`float DHTesp::computeAbsoluteHumidity(float temperature, float percentHumidity, bool isFahrenheit)`**

But in the code you use
**`absHumidity *= humidity;`**
I think that should be
**`absHumidity *= percentHumidity;`**
percentHumidity is not used in the function and humidity is a private variable.
Typo???
Can you correct and resubmit the pull request.

**Comment by tonnico** [comment]
> Typo???

Yes, good catch.
> Can you correct and resubmit the pull request.

Done.

**Comment by beegee-tokyo** [comment]
Perfect. Merged.

**Pull request merged**
