### PR TITLE
Power reduction and readings fix.

### PR DESCRIPTION
**Pull request by Swiftyhu**
Improvement: 
 Reduce CPU usage by adding a delay in the measurement loop.

Fix:
 Added decimal part to the read values for DHT11. (However the humidity readings do not change... :) )

### CODE REVIEW

**Comment by beegee-tokyo** [comment]
I will have to test it, but I don't think it is a good idea.
**a) 5ms delay**
You are adding a 5ms delay in the loop that is surrounded by 
```noInterrupts();``` (None ESP32 devices)
and 
```portENTER_CRITICAL(&mux);``` (ESP32 devices)
And the reading from the DHT sensors is difficult already because the loop has to count the time. Even this short delay might disturb the proper readings.
**b) adding decimal part**
Not sure if that makes any sense at all for the DHT11 because this sensor has an accuracy of only ±2℃ anyway. Even if the data sheet says that the values come with integral and decimal parts, I don't see any improvement by using the decimal parts.

**Comment by Swiftyhu** [comment]
I tested both patches...  And... WorksForMe... :)

a) There was no change in the data when I added this delay. I'll provide you some extra info about how many times gets the loop executed with and without the delay.

b) I agree that the sensor accuracy is lower. However I think the library itself should change the data what we get from then sensor...

**Comment by Swiftyhu** [comment]
Hi again!

I think I have to take back the delay patch. It does nothing... I think the compiler simply ignores the delay at that point.

I did measure the count of iterations with and without the delay. The difference is insignificant.

Sorry about that patch.

**Comment by beegee-tokyo** [comment]
The delay is already out. It caused problems on ESP8266. See issue #38

**Pull request merged**
