### PR TITLE
Added getPin function

### PR DESCRIPTION
**Pull request by AndreyShamis**
Signed-off-by: Andrey Shamis <lolnik@gmail.com>

### CODE REVIEW

**Comment by beegee-tokyo** [comment]
Why do you need this? The GPIO you connected the DHT sensor to is known from the declaration?

**Comment by AndreyShamis** [comment]
> Why do you need this? The GPIO you connected the DHT sensor to is known from the declaration?

Hi
Yes you are pretty right - when this is only single device this function is useless.
But in case where there is many devices connected and you need to distinguish between them, it can be helpful. Sure its possible to create and maintain self code for save the ids, but the variable already defined, so why just not to provide the functionality to read it...

Thanks

**Comment by beegee-tokyo** [comment]
Got it.
Didn't think about multiple sensor scenarios. Need to change the library descriptions for proper updates in Arduino IDE.

Will do it tomorrow.

**Comment by beegee-tokyo** [comment]
New version released. Will take a day or 2 before it shows up in ArduinoIDE
and PlatformIO.

Thanks for your contribution.

kind regards
mit freundlichem Gruss

Bernd Giesecke

**Comment by AndreyShamis** [comment]
Thanks

**Pull request merged**
